"""empty message

Revision ID: 617456bc9d8c
Revises: 51a73d55254
Create Date: 2016-02-01 23:30:38.960590

"""

# revision identifiers, used by Alembic.
revision = '617456bc9d8c'
down_revision = '51a73d55254'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_version')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_version',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.NUMERIC(precision=1137), nullable=True),
    sa.Column('registered', sa.BOOLEAN(), nullable=True),
    sa.Column('admin', sa.BOOLEAN(), nullable=True),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('end_transaction_id', sa.INTEGER(), nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    ### end Alembic commands ###
