"""empty message

Revision ID: d5e28ae20d48
Revises: 617456bc9d8c
Create Date: 2018-05-28 00:31:52.158920

"""

# revision identifiers, used by Alembic.
revision = 'd5e28ae20d48'
down_revision = '617456bc9d8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('multiple_correct', sa.Boolean(), server_default=sa.literal(False), nullable=False))
    op.add_column('exam_version', sa.Column('multiple_correct', sa.Boolean(), server_default=sa.literal(False), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_version', 'multiple_correct')
    op.drop_column('exam', 'multiple_correct')
    # ### end Alembic commands ###
